### ISSUE TITLE
Nav bar and Home page

### ISSUE THREAD

**Issue by rogink** [pompeybug/pompeybug.github.io#2]
Rich - can we have a nav bar similar to old one, e.g. for events, contact, joining? The community page can go and put a prominent link on that page.  Maybe add a 'social media' page for links to Facebook, Twitter.

The long banner picture works well so would be good to see on the new site.

Cheers
Roger

**Comment by ear1grey** [comment]
Social media page added to menu.

Menu can be horizontally or vertically configured.  personally I prefer vertical because it's easier to scan down.

The long banner adds no information to the page, and eventually we're going to want to add advertising there/somewhere so keeping it as simple as possible is preferable to me.
